version: "3"

services:
  php:
    build: 
      context: ./php
    volumes: 
      - ./site:/var/www/html
    expose:
      - "9010"  # Expose PHP-FPM port

  nginx:
    image: nginx:alpine
    ports:
      - "3003:80"
    volumes:
      - ./site:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: 1111
      TZ: Asia/Bangkok
    volumes: 
      - ./mysql_db:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment: 
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports: 
      - "3004:80"
